
#define HAVE_C99_VARARGS_MACROS 1

#define HAVE_LIBM 1
#define HAVE_LIMITS_H 1
#define HAVE_MATH_H 1
#define HAVE_STDARG_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
